/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVendorsImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedTrainsImport } from './routes/_authenticated/trains'
import { Route as AuthenticatedTemplatesImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedStationsImport } from './routes/_authenticated/stations'
import { Route as AuthenticatedRestreqImport } from './routes/_authenticated/restreq'
import { Route as AuthenticatedRequestsImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedReportsImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRatingsImport } from './routes/_authenticated/ratings'
import { Route as AuthenticatedPendingoutletsImport } from './routes/_authenticated/pendingoutlets'
import { Route as AuthenticatedPayoutHistoryImport } from './routes/_authenticated/payout-history'
import { Route as AuthenticatedOutletsImport } from './routes/_authenticated/outlets'
import { Route as AuthenticatedOrdersImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedNewitemreqImport } from './routes/_authenticated/newitemreq'
import { Route as AuthenticatedItemreqImport } from './routes/_authenticated/itemreq'
import { Route as AuthenticatedInactiveoutletsImport } from './routes/_authenticated/inactiveoutlets'
import { Route as AuthenticatedHrImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedFssaiexpImport } from './routes/_authenticated/fssaiexp'
import { Route as AuthenticatedEmployeesImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDepartmentsImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDelitemreqImport } from './routes/_authenticated/delitemreq'
import { Route as AuthenticatedDeletedoutletsImport } from './routes/_authenticated/deletedoutlets'
import { Route as AuthenticatedCustqueImport } from './routes/_authenticated/custque'
import { Route as AuthenticatedCreateOrderImport } from './routes/_authenticated/create-order'
import { Route as AuthenticatedComplaintsImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedComplaintReportsImport } from './routes/_authenticated/complaint-reports'
import { Route as AuthenticatedBlogsImport } from './routes/_authenticated/blogs'
import { Route as AuthenticatedAllqueImport } from './routes/_authenticated/allque'
import { Route as AuthenticatedAlloutletsImport } from './routes/_authenticated/alloutlets'
import { Route as AuthenticatedRolesImport } from './routes/_authenticated/Roles'
import { Route as AuthenticatedWalletOutletidImport } from './routes/_authenticated/wallet.$outletid'
import { Route as AuthenticatedPendingmenuOutletidImport } from './routes/_authenticated/pendingmenu.$outletid'
import { Route as AuthenticatedOutordersOutletidImport } from './routes/_authenticated/outorders.$outletid'
import { Route as AuthenticatedOutletStationcodeImport } from './routes/_authenticated/outlet.$stationcode'
import { Route as AuthenticatedMenuOutletidImport } from './routes/_authenticated/menu.$outletid'
import { Route as AuthenticatedFeedbacksOutletidImport } from './routes/_authenticated/feedbacks.$outletid'
import { Route as AuthenticatedDeliveryOutletidImport } from './routes/_authenticated/delivery.$outletid'
import { Route as AuthenticatedAttendanceEmpidImport } from './routes/_authenticated/attendance.$empid'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedVendorsRoute = AuthenticatedVendorsImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedTrainsRoute = AuthenticatedTrainsImport.update({
  id: '/trains',
  path: '/trains',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedTemplatesRoute = AuthenticatedTemplatesImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedStationsRoute = AuthenticatedStationsImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRestreqRoute = AuthenticatedRestreqImport.update({
  id: '/restreq',
  path: '/restreq',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRequestsRoute = AuthenticatedRequestsImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedReportsRoute = AuthenticatedReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRatingsRoute = AuthenticatedRatingsImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedPendingoutletsRoute =
  AuthenticatedPendingoutletsImport.update({
    id: '/pendingoutlets',
    path: '/pendingoutlets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPayoutHistoryRoute = AuthenticatedPayoutHistoryImport.update(
  {
    id: '/payout-history',
    path: '/payout-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedOutletsRoute = AuthenticatedOutletsImport.update({
  id: '/outlets',
  path: '/outlets',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedOrdersRoute = AuthenticatedOrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedNewitemreqRoute = AuthenticatedNewitemreqImport.update({
  id: '/newitemreq',
  path: '/newitemreq',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedItemreqRoute = AuthenticatedItemreqImport.update({
  id: '/itemreq',
  path: '/itemreq',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedInactiveoutletsRoute =
  AuthenticatedInactiveoutletsImport.update({
    id: '/inactiveoutlets',
    path: '/inactiveoutlets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedHrRoute = AuthenticatedHrImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedFssaiexpRoute = AuthenticatedFssaiexpImport.update({
  id: '/fssaiexp',
  path: '/fssaiexp',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedEmployeesRoute = AuthenticatedEmployeesImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDepartmentsRoute = AuthenticatedDepartmentsImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDelitemreqRoute = AuthenticatedDelitemreqImport.update({
  id: '/delitemreq',
  path: '/delitemreq',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDeletedoutletsRoute =
  AuthenticatedDeletedoutletsImport.update({
    id: '/deletedoutlets',
    path: '/deletedoutlets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedCustqueRoute = AuthenticatedCustqueImport.update({
  id: '/custque',
  path: '/custque',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCreateOrderRoute = AuthenticatedCreateOrderImport.update({
  id: '/create-order',
  path: '/create-order',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedComplaintsRoute = AuthenticatedComplaintsImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedComplaintReportsRoute =
  AuthenticatedComplaintReportsImport.update({
    id: '/complaint-reports',
    path: '/complaint-reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedBlogsRoute = AuthenticatedBlogsImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAllqueRoute = AuthenticatedAllqueImport.update({
  id: '/allque',
  path: '/allque',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAlloutletsRoute = AuthenticatedAlloutletsImport.update({
  id: '/alloutlets',
  path: '/alloutlets',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRolesRoute = AuthenticatedRolesImport.update({
  id: '/Roles',
  path: '/Roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedWalletOutletidRoute =
  AuthenticatedWalletOutletidImport.update({
    id: '/wallet/$outletid',
    path: '/wallet/$outletid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPendingmenuOutletidRoute =
  AuthenticatedPendingmenuOutletidImport.update({
    id: '/pendingmenu/$outletid',
    path: '/pendingmenu/$outletid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedOutordersOutletidRoute =
  AuthenticatedOutordersOutletidImport.update({
    id: '/outorders/$outletid',
    path: '/outorders/$outletid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedOutletStationcodeRoute =
  AuthenticatedOutletStationcodeImport.update({
    id: '/outlet/$stationcode',
    path: '/outlet/$stationcode',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedMenuOutletidRoute = AuthenticatedMenuOutletidImport.update({
  id: '/menu/$outletid',
  path: '/menu/$outletid',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedFeedbacksOutletidRoute =
  AuthenticatedFeedbacksOutletidImport.update({
    id: '/feedbacks/$outletid',
    path: '/feedbacks/$outletid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDeliveryOutletidRoute =
  AuthenticatedDeliveryOutletidImport.update({
    id: '/delivery/$outletid',
    path: '/delivery/$outletid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAttendanceEmpidRoute =
  AuthenticatedAttendanceEmpidImport.update({
    id: '/attendance/$empid',
    path: '/attendance/$empid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/Roles': {
      id: '/_authenticated/Roles'
      path: '/Roles'
      fullPath: '/Roles'
      preLoaderRoute: typeof AuthenticatedRolesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/alloutlets': {
      id: '/_authenticated/alloutlets'
      path: '/alloutlets'
      fullPath: '/alloutlets'
      preLoaderRoute: typeof AuthenticatedAlloutletsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/allque': {
      id: '/_authenticated/allque'
      path: '/allque'
      fullPath: '/allque'
      preLoaderRoute: typeof AuthenticatedAllqueImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/blogs': {
      id: '/_authenticated/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof AuthenticatedBlogsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/complaint-reports': {
      id: '/_authenticated/complaint-reports'
      path: '/complaint-reports'
      fullPath: '/complaint-reports'
      preLoaderRoute: typeof AuthenticatedComplaintReportsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/create-order': {
      id: '/_authenticated/create-order'
      path: '/create-order'
      fullPath: '/create-order'
      preLoaderRoute: typeof AuthenticatedCreateOrderImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/custque': {
      id: '/_authenticated/custque'
      path: '/custque'
      fullPath: '/custque'
      preLoaderRoute: typeof AuthenticatedCustqueImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/deletedoutlets': {
      id: '/_authenticated/deletedoutlets'
      path: '/deletedoutlets'
      fullPath: '/deletedoutlets'
      preLoaderRoute: typeof AuthenticatedDeletedoutletsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/delitemreq': {
      id: '/_authenticated/delitemreq'
      path: '/delitemreq'
      fullPath: '/delitemreq'
      preLoaderRoute: typeof AuthenticatedDelitemreqImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/fssaiexp': {
      id: '/_authenticated/fssaiexp'
      path: '/fssaiexp'
      fullPath: '/fssaiexp'
      preLoaderRoute: typeof AuthenticatedFssaiexpImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/inactiveoutlets': {
      id: '/_authenticated/inactiveoutlets'
      path: '/inactiveoutlets'
      fullPath: '/inactiveoutlets'
      preLoaderRoute: typeof AuthenticatedInactiveoutletsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/itemreq': {
      id: '/_authenticated/itemreq'
      path: '/itemreq'
      fullPath: '/itemreq'
      preLoaderRoute: typeof AuthenticatedItemreqImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/newitemreq': {
      id: '/_authenticated/newitemreq'
      path: '/newitemreq'
      fullPath: '/newitemreq'
      preLoaderRoute: typeof AuthenticatedNewitemreqImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/outlets': {
      id: '/_authenticated/outlets'
      path: '/outlets'
      fullPath: '/outlets'
      preLoaderRoute: typeof AuthenticatedOutletsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/payout-history': {
      id: '/_authenticated/payout-history'
      path: '/payout-history'
      fullPath: '/payout-history'
      preLoaderRoute: typeof AuthenticatedPayoutHistoryImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/pendingoutlets': {
      id: '/_authenticated/pendingoutlets'
      path: '/pendingoutlets'
      fullPath: '/pendingoutlets'
      preLoaderRoute: typeof AuthenticatedPendingoutletsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/ratings': {
      id: '/_authenticated/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof AuthenticatedRatingsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/restreq': {
      id: '/_authenticated/restreq'
      path: '/restreq'
      fullPath: '/restreq'
      preLoaderRoute: typeof AuthenticatedRestreqImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/stations': {
      id: '/_authenticated/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof AuthenticatedStationsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/trains': {
      id: '/_authenticated/trains'
      path: '/trains'
      fullPath: '/trains'
      preLoaderRoute: typeof AuthenticatedTrainsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/attendance/$empid': {
      id: '/_authenticated/attendance/$empid'
      path: '/attendance/$empid'
      fullPath: '/attendance/$empid'
      preLoaderRoute: typeof AuthenticatedAttendanceEmpidImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/delivery/$outletid': {
      id: '/_authenticated/delivery/$outletid'
      path: '/delivery/$outletid'
      fullPath: '/delivery/$outletid'
      preLoaderRoute: typeof AuthenticatedDeliveryOutletidImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/feedbacks/$outletid': {
      id: '/_authenticated/feedbacks/$outletid'
      path: '/feedbacks/$outletid'
      fullPath: '/feedbacks/$outletid'
      preLoaderRoute: typeof AuthenticatedFeedbacksOutletidImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/menu/$outletid': {
      id: '/_authenticated/menu/$outletid'
      path: '/menu/$outletid'
      fullPath: '/menu/$outletid'
      preLoaderRoute: typeof AuthenticatedMenuOutletidImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/outlet/$stationcode': {
      id: '/_authenticated/outlet/$stationcode'
      path: '/outlet/$stationcode'
      fullPath: '/outlet/$stationcode'
      preLoaderRoute: typeof AuthenticatedOutletStationcodeImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/outorders/$outletid': {
      id: '/_authenticated/outorders/$outletid'
      path: '/outorders/$outletid'
      fullPath: '/outorders/$outletid'
      preLoaderRoute: typeof AuthenticatedOutordersOutletidImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/pendingmenu/$outletid': {
      id: '/_authenticated/pendingmenu/$outletid'
      path: '/pendingmenu/$outletid'
      fullPath: '/pendingmenu/$outletid'
      preLoaderRoute: typeof AuthenticatedPendingmenuOutletidImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/wallet/$outletid': {
      id: '/_authenticated/wallet/$outletid'
      path: '/wallet/$outletid'
      fullPath: '/wallet/$outletid'
      preLoaderRoute: typeof AuthenticatedWalletOutletidImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedAlloutletsRoute: typeof AuthenticatedAlloutletsRoute
  AuthenticatedAllqueRoute: typeof AuthenticatedAllqueRoute
  AuthenticatedBlogsRoute: typeof AuthenticatedBlogsRoute
  AuthenticatedComplaintReportsRoute: typeof AuthenticatedComplaintReportsRoute
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRoute
  AuthenticatedCreateOrderRoute: typeof AuthenticatedCreateOrderRoute
  AuthenticatedCustqueRoute: typeof AuthenticatedCustqueRoute
  AuthenticatedDeletedoutletsRoute: typeof AuthenticatedDeletedoutletsRoute
  AuthenticatedDelitemreqRoute: typeof AuthenticatedDelitemreqRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedFssaiexpRoute: typeof AuthenticatedFssaiexpRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedInactiveoutletsRoute: typeof AuthenticatedInactiveoutletsRoute
  AuthenticatedItemreqRoute: typeof AuthenticatedItemreqRoute
  AuthenticatedNewitemreqRoute: typeof AuthenticatedNewitemreqRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedOutletsRoute: typeof AuthenticatedOutletsRoute
  AuthenticatedPayoutHistoryRoute: typeof AuthenticatedPayoutHistoryRoute
  AuthenticatedPendingoutletsRoute: typeof AuthenticatedPendingoutletsRoute
  AuthenticatedRatingsRoute: typeof AuthenticatedRatingsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedRestreqRoute: typeof AuthenticatedRestreqRoute
  AuthenticatedStationsRoute: typeof AuthenticatedStationsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedTrainsRoute: typeof AuthenticatedTrainsRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAttendanceEmpidRoute: typeof AuthenticatedAttendanceEmpidRoute
  AuthenticatedDeliveryOutletidRoute: typeof AuthenticatedDeliveryOutletidRoute
  AuthenticatedFeedbacksOutletidRoute: typeof AuthenticatedFeedbacksOutletidRoute
  AuthenticatedMenuOutletidRoute: typeof AuthenticatedMenuOutletidRoute
  AuthenticatedOutletStationcodeRoute: typeof AuthenticatedOutletStationcodeRoute
  AuthenticatedOutordersOutletidRoute: typeof AuthenticatedOutordersOutletidRoute
  AuthenticatedPendingmenuOutletidRoute: typeof AuthenticatedPendingmenuOutletidRoute
  AuthenticatedWalletOutletidRoute: typeof AuthenticatedWalletOutletidRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedAlloutletsRoute: AuthenticatedAlloutletsRoute,
  AuthenticatedAllqueRoute: AuthenticatedAllqueRoute,
  AuthenticatedBlogsRoute: AuthenticatedBlogsRoute,
  AuthenticatedComplaintReportsRoute: AuthenticatedComplaintReportsRoute,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRoute,
  AuthenticatedCreateOrderRoute: AuthenticatedCreateOrderRoute,
  AuthenticatedCustqueRoute: AuthenticatedCustqueRoute,
  AuthenticatedDeletedoutletsRoute: AuthenticatedDeletedoutletsRoute,
  AuthenticatedDelitemreqRoute: AuthenticatedDelitemreqRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedFssaiexpRoute: AuthenticatedFssaiexpRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedInactiveoutletsRoute: AuthenticatedInactiveoutletsRoute,
  AuthenticatedItemreqRoute: AuthenticatedItemreqRoute,
  AuthenticatedNewitemreqRoute: AuthenticatedNewitemreqRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedOutletsRoute: AuthenticatedOutletsRoute,
  AuthenticatedPayoutHistoryRoute: AuthenticatedPayoutHistoryRoute,
  AuthenticatedPendingoutletsRoute: AuthenticatedPendingoutletsRoute,
  AuthenticatedRatingsRoute: AuthenticatedRatingsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedRestreqRoute: AuthenticatedRestreqRoute,
  AuthenticatedStationsRoute: AuthenticatedStationsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedTrainsRoute: AuthenticatedTrainsRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAttendanceEmpidRoute: AuthenticatedAttendanceEmpidRoute,
  AuthenticatedDeliveryOutletidRoute: AuthenticatedDeliveryOutletidRoute,
  AuthenticatedFeedbacksOutletidRoute: AuthenticatedFeedbacksOutletidRoute,
  AuthenticatedMenuOutletidRoute: AuthenticatedMenuOutletidRoute,
  AuthenticatedOutletStationcodeRoute: AuthenticatedOutletStationcodeRoute,
  AuthenticatedOutordersOutletidRoute: AuthenticatedOutordersOutletidRoute,
  AuthenticatedPendingmenuOutletidRoute: AuthenticatedPendingmenuOutletidRoute,
  AuthenticatedWalletOutletidRoute: AuthenticatedWalletOutletidRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/Roles': typeof AuthenticatedRolesRoute
  '/alloutlets': typeof AuthenticatedAlloutletsRoute
  '/allque': typeof AuthenticatedAllqueRoute
  '/blogs': typeof AuthenticatedBlogsRoute
  '/complaint-reports': typeof AuthenticatedComplaintReportsRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/create-order': typeof AuthenticatedCreateOrderRoute
  '/custque': typeof AuthenticatedCustqueRoute
  '/deletedoutlets': typeof AuthenticatedDeletedoutletsRoute
  '/delitemreq': typeof AuthenticatedDelitemreqRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/fssaiexp': typeof AuthenticatedFssaiexpRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inactiveoutlets': typeof AuthenticatedInactiveoutletsRoute
  '/itemreq': typeof AuthenticatedItemreqRoute
  '/newitemreq': typeof AuthenticatedNewitemreqRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/outlets': typeof AuthenticatedOutletsRoute
  '/payout-history': typeof AuthenticatedPayoutHistoryRoute
  '/pendingoutlets': typeof AuthenticatedPendingoutletsRoute
  '/ratings': typeof AuthenticatedRatingsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/restreq': typeof AuthenticatedRestreqRoute
  '/stations': typeof AuthenticatedStationsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/trains': typeof AuthenticatedTrainsRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/': typeof AuthenticatedIndexRoute
  '/attendance/$empid': typeof AuthenticatedAttendanceEmpidRoute
  '/delivery/$outletid': typeof AuthenticatedDeliveryOutletidRoute
  '/feedbacks/$outletid': typeof AuthenticatedFeedbacksOutletidRoute
  '/menu/$outletid': typeof AuthenticatedMenuOutletidRoute
  '/outlet/$stationcode': typeof AuthenticatedOutletStationcodeRoute
  '/outorders/$outletid': typeof AuthenticatedOutordersOutletidRoute
  '/pendingmenu/$outletid': typeof AuthenticatedPendingmenuOutletidRoute
  '/wallet/$outletid': typeof AuthenticatedWalletOutletidRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/Roles': typeof AuthenticatedRolesRoute
  '/alloutlets': typeof AuthenticatedAlloutletsRoute
  '/allque': typeof AuthenticatedAllqueRoute
  '/blogs': typeof AuthenticatedBlogsRoute
  '/complaint-reports': typeof AuthenticatedComplaintReportsRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/create-order': typeof AuthenticatedCreateOrderRoute
  '/custque': typeof AuthenticatedCustqueRoute
  '/deletedoutlets': typeof AuthenticatedDeletedoutletsRoute
  '/delitemreq': typeof AuthenticatedDelitemreqRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/fssaiexp': typeof AuthenticatedFssaiexpRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inactiveoutlets': typeof AuthenticatedInactiveoutletsRoute
  '/itemreq': typeof AuthenticatedItemreqRoute
  '/newitemreq': typeof AuthenticatedNewitemreqRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/outlets': typeof AuthenticatedOutletsRoute
  '/payout-history': typeof AuthenticatedPayoutHistoryRoute
  '/pendingoutlets': typeof AuthenticatedPendingoutletsRoute
  '/ratings': typeof AuthenticatedRatingsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/restreq': typeof AuthenticatedRestreqRoute
  '/stations': typeof AuthenticatedStationsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/trains': typeof AuthenticatedTrainsRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/': typeof AuthenticatedIndexRoute
  '/attendance/$empid': typeof AuthenticatedAttendanceEmpidRoute
  '/delivery/$outletid': typeof AuthenticatedDeliveryOutletidRoute
  '/feedbacks/$outletid': typeof AuthenticatedFeedbacksOutletidRoute
  '/menu/$outletid': typeof AuthenticatedMenuOutletidRoute
  '/outlet/$stationcode': typeof AuthenticatedOutletStationcodeRoute
  '/outorders/$outletid': typeof AuthenticatedOutordersOutletidRoute
  '/pendingmenu/$outletid': typeof AuthenticatedPendingmenuOutletidRoute
  '/wallet/$outletid': typeof AuthenticatedWalletOutletidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/Roles': typeof AuthenticatedRolesRoute
  '/_authenticated/alloutlets': typeof AuthenticatedAlloutletsRoute
  '/_authenticated/allque': typeof AuthenticatedAllqueRoute
  '/_authenticated/blogs': typeof AuthenticatedBlogsRoute
  '/_authenticated/complaint-reports': typeof AuthenticatedComplaintReportsRoute
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRoute
  '/_authenticated/create-order': typeof AuthenticatedCreateOrderRoute
  '/_authenticated/custque': typeof AuthenticatedCustqueRoute
  '/_authenticated/deletedoutlets': typeof AuthenticatedDeletedoutletsRoute
  '/_authenticated/delitemreq': typeof AuthenticatedDelitemreqRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/fssaiexp': typeof AuthenticatedFssaiexpRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/inactiveoutlets': typeof AuthenticatedInactiveoutletsRoute
  '/_authenticated/itemreq': typeof AuthenticatedItemreqRoute
  '/_authenticated/newitemreq': typeof AuthenticatedNewitemreqRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/outlets': typeof AuthenticatedOutletsRoute
  '/_authenticated/payout-history': typeof AuthenticatedPayoutHistoryRoute
  '/_authenticated/pendingoutlets': typeof AuthenticatedPendingoutletsRoute
  '/_authenticated/ratings': typeof AuthenticatedRatingsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/restreq': typeof AuthenticatedRestreqRoute
  '/_authenticated/stations': typeof AuthenticatedStationsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/trains': typeof AuthenticatedTrainsRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/attendance/$empid': typeof AuthenticatedAttendanceEmpidRoute
  '/_authenticated/delivery/$outletid': typeof AuthenticatedDeliveryOutletidRoute
  '/_authenticated/feedbacks/$outletid': typeof AuthenticatedFeedbacksOutletidRoute
  '/_authenticated/menu/$outletid': typeof AuthenticatedMenuOutletidRoute
  '/_authenticated/outlet/$stationcode': typeof AuthenticatedOutletStationcodeRoute
  '/_authenticated/outorders/$outletid': typeof AuthenticatedOutordersOutletidRoute
  '/_authenticated/pendingmenu/$outletid': typeof AuthenticatedPendingmenuOutletidRoute
  '/_authenticated/wallet/$outletid': typeof AuthenticatedWalletOutletidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/Roles'
    | '/alloutlets'
    | '/allque'
    | '/blogs'
    | '/complaint-reports'
    | '/complaints'
    | '/create-order'
    | '/custque'
    | '/deletedoutlets'
    | '/delitemreq'
    | '/departments'
    | '/employees'
    | '/fssaiexp'
    | '/hr'
    | '/inactiveoutlets'
    | '/itemreq'
    | '/newitemreq'
    | '/orders'
    | '/outlets'
    | '/payout-history'
    | '/pendingoutlets'
    | '/ratings'
    | '/reports'
    | '/requests'
    | '/restreq'
    | '/stations'
    | '/templates'
    | '/trains'
    | '/vendors'
    | '/'
    | '/attendance/$empid'
    | '/delivery/$outletid'
    | '/feedbacks/$outletid'
    | '/menu/$outletid'
    | '/outlet/$stationcode'
    | '/outorders/$outletid'
    | '/pendingmenu/$outletid'
    | '/wallet/$outletid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/Roles'
    | '/alloutlets'
    | '/allque'
    | '/blogs'
    | '/complaint-reports'
    | '/complaints'
    | '/create-order'
    | '/custque'
    | '/deletedoutlets'
    | '/delitemreq'
    | '/departments'
    | '/employees'
    | '/fssaiexp'
    | '/hr'
    | '/inactiveoutlets'
    | '/itemreq'
    | '/newitemreq'
    | '/orders'
    | '/outlets'
    | '/payout-history'
    | '/pendingoutlets'
    | '/ratings'
    | '/reports'
    | '/requests'
    | '/restreq'
    | '/stations'
    | '/templates'
    | '/trains'
    | '/vendors'
    | '/'
    | '/attendance/$empid'
    | '/delivery/$outletid'
    | '/feedbacks/$outletid'
    | '/menu/$outletid'
    | '/outlet/$stationcode'
    | '/outorders/$outletid'
    | '/pendingmenu/$outletid'
    | '/wallet/$outletid'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/Roles'
    | '/_authenticated/alloutlets'
    | '/_authenticated/allque'
    | '/_authenticated/blogs'
    | '/_authenticated/complaint-reports'
    | '/_authenticated/complaints'
    | '/_authenticated/create-order'
    | '/_authenticated/custque'
    | '/_authenticated/deletedoutlets'
    | '/_authenticated/delitemreq'
    | '/_authenticated/departments'
    | '/_authenticated/employees'
    | '/_authenticated/fssaiexp'
    | '/_authenticated/hr'
    | '/_authenticated/inactiveoutlets'
    | '/_authenticated/itemreq'
    | '/_authenticated/newitemreq'
    | '/_authenticated/orders'
    | '/_authenticated/outlets'
    | '/_authenticated/payout-history'
    | '/_authenticated/pendingoutlets'
    | '/_authenticated/ratings'
    | '/_authenticated/reports'
    | '/_authenticated/requests'
    | '/_authenticated/restreq'
    | '/_authenticated/stations'
    | '/_authenticated/templates'
    | '/_authenticated/trains'
    | '/_authenticated/vendors'
    | '/_authenticated/'
    | '/_authenticated/attendance/$empid'
    | '/_authenticated/delivery/$outletid'
    | '/_authenticated/feedbacks/$outletid'
    | '/_authenticated/menu/$outletid'
    | '/_authenticated/outlet/$stationcode'
    | '/_authenticated/outorders/$outletid'
    | '/_authenticated/pendingmenu/$outletid'
    | '/_authenticated/wallet/$outletid'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/Roles",
        "/_authenticated/alloutlets",
        "/_authenticated/allque",
        "/_authenticated/blogs",
        "/_authenticated/complaint-reports",
        "/_authenticated/complaints",
        "/_authenticated/create-order",
        "/_authenticated/custque",
        "/_authenticated/deletedoutlets",
        "/_authenticated/delitemreq",
        "/_authenticated/departments",
        "/_authenticated/employees",
        "/_authenticated/fssaiexp",
        "/_authenticated/hr",
        "/_authenticated/inactiveoutlets",
        "/_authenticated/itemreq",
        "/_authenticated/newitemreq",
        "/_authenticated/orders",
        "/_authenticated/outlets",
        "/_authenticated/payout-history",
        "/_authenticated/pendingoutlets",
        "/_authenticated/ratings",
        "/_authenticated/reports",
        "/_authenticated/requests",
        "/_authenticated/restreq",
        "/_authenticated/stations",
        "/_authenticated/templates",
        "/_authenticated/trains",
        "/_authenticated/vendors",
        "/_authenticated/",
        "/_authenticated/attendance/$empid",
        "/_authenticated/delivery/$outletid",
        "/_authenticated/feedbacks/$outletid",
        "/_authenticated/menu/$outletid",
        "/_authenticated/outlet/$stationcode",
        "/_authenticated/outorders/$outletid",
        "/_authenticated/pendingmenu/$outletid",
        "/_authenticated/wallet/$outletid"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/Roles": {
      "filePath": "_authenticated/Roles.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/alloutlets": {
      "filePath": "_authenticated/alloutlets.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/allque": {
      "filePath": "_authenticated/allque.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/blogs": {
      "filePath": "_authenticated/blogs.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/complaint-reports": {
      "filePath": "_authenticated/complaint-reports.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/complaints": {
      "filePath": "_authenticated/complaints.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/create-order": {
      "filePath": "_authenticated/create-order.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/custque": {
      "filePath": "_authenticated/custque.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/deletedoutlets": {
      "filePath": "_authenticated/deletedoutlets.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/delitemreq": {
      "filePath": "_authenticated/delitemreq.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/departments": {
      "filePath": "_authenticated/departments.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/employees": {
      "filePath": "_authenticated/employees.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/fssaiexp": {
      "filePath": "_authenticated/fssaiexp.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/hr": {
      "filePath": "_authenticated/hr.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/inactiveoutlets": {
      "filePath": "_authenticated/inactiveoutlets.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/itemreq": {
      "filePath": "_authenticated/itemreq.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/newitemreq": {
      "filePath": "_authenticated/newitemreq.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/orders": {
      "filePath": "_authenticated/orders.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/outlets": {
      "filePath": "_authenticated/outlets.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/payout-history": {
      "filePath": "_authenticated/payout-history.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/pendingoutlets": {
      "filePath": "_authenticated/pendingoutlets.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/ratings": {
      "filePath": "_authenticated/ratings.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/reports": {
      "filePath": "_authenticated/reports.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/requests": {
      "filePath": "_authenticated/requests.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/restreq": {
      "filePath": "_authenticated/restreq.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/stations": {
      "filePath": "_authenticated/stations.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/templates": {
      "filePath": "_authenticated/templates.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/trains": {
      "filePath": "_authenticated/trains.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/vendors": {
      "filePath": "_authenticated/vendors.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/attendance/$empid": {
      "filePath": "_authenticated/attendance.$empid.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/delivery/$outletid": {
      "filePath": "_authenticated/delivery.$outletid.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/feedbacks/$outletid": {
      "filePath": "_authenticated/feedbacks.$outletid.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/menu/$outletid": {
      "filePath": "_authenticated/menu.$outletid.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/outlet/$stationcode": {
      "filePath": "_authenticated/outlet.$stationcode.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/outorders/$outletid": {
      "filePath": "_authenticated/outorders.$outletid.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/pendingmenu/$outletid": {
      "filePath": "_authenticated/pendingmenu.$outletid.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/wallet/$outletid": {
      "filePath": "_authenticated/wallet.$outletid.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
